---
label: Product
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
    max: 140
  label: Name
- name: sku
  type: number
  label: SKU
  description: Must be unique
  default: 
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: price
  type: number
  label: Price
  description: ''
  default: 5.99
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: weight__display_
  type: text
  config:
    required: true
  label: Weight (Display)
  description: Displayed to the user, include units.
  default: 1 lb
- name: weight
  type: number
  label: Weight (ounces)
  description: Not displayed, used for shipping weight in Snipcart
  default: 16
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: image
  type: file
  config:
    maxSize: 5
  label: Image
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
    max: 800
  label: Description
- name: product_options
  type: field_group_list
  fields:
  - name: option_name
    type: text
    config:
      required: true
    label: Option Name
  - name: option_price
    type: number
    label: Option Price
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
      required: false
  config:
    min: 
    max: 
    labelField: 
  label: Product Options
  description: If using options, include option for default or base product as well.
- name: tags
  type: tag_list
  default: []
  label: Extra Categories
  description: Product will appear in these categories in addition to whatever folder
    it's under, which will be it's primary category.
- name: layout
  type: text
  config:
    required: false
  label: Layout
  hidden: true
  default: product
- name: seo
  type: include
  config: {}
  template: seo
  label: SEO
  description: These fields are not required and only need to be filled out if you're
    overriding what's on the page.
- name: banner
  type: include
  config: {}
  template: banner
  label: Banner
pages:
- site/products/Chicken/crawfish-rice-chicken.md
- site/products/Fresh Sausage/fresh-sausage.md
- site/products/Stuffed Boneless Chicken Breasts/stuffed-breasts.md
- site/products/Stuffed Boneless Chicken Thighs/stuffed-chicken-thighs.md
- site/products/Stuffed Boneless Pork Tenderloin/pork-tenderloin-stuffed.md
- site/products/Stuffed Boneless Pork Tenderloin/seasoned-tenderloin-tip.md
- site/products/boudin/deer-boudin.md
- site/products/boudin/pork-boudin.md
- site/products/boudin/smoked-boudin.md
- site/products/game/duck-breast-jal-cc.md
- site/products/game/seasoned-duck-breast.md
- site/products/game/stuffed-rabbit.md
- site/products/game/whole-quail-stuffed.md
- site/products/game/whole-rabbit.md
- site/products/hand-cut-steaks/filet-mignon.md
- site/products/hand-cut-steaks/porterhouse-steak.md
- site/products/hand-cut-steaks/season-choice-blackangus-ribeye.md
- site/products/hand-cut-steaks/stuffed-ribeye-jalapeno-creamcheese.md
- site/products/heat-and-eat/9-crabmeat-pie.md
- site/products/heat-and-eat/9-crawfish-pie.md
- site/products/heat-and-eat/alligator-sauce-piquant.md
- site/products/heat-and-eat/chicken-sauce-piquant.md
- site/products/heat-and-eat/chicken-sausage-gumbo.md
- site/products/heat-and-eat/chili.md
- site/products/heat-and-eat/corn-maque-choux.md
- site/products/heat-and-eat/cornbread-dressing.md
- site/products/heat-and-eat/crawfish-corn-soup.md
- site/products/heat-and-eat/creamed-spinach-pan.md
- site/products/heat-and-eat/duck-andouille-gumbo.md
- site/products/heat-and-eat/flame-roasted-corn.md
- site/products/heat-and-eat/green-bean-pan.md
- site/products/heat-and-eat/guacamole.md
- site/products/heat-and-eat/heat-and-eat.md
- site/products/heat-and-eat/pastalaya.md
- site/products/heat-and-eat/potato-pan.md
- site/products/heat-and-eat/red-beans-sausage.md
- site/products/heat-and-eat/seafood-gumbo.md
- site/products/heat-and-eat/shrimp-corn-soup.md
- site/products/heat-and-eat/shrimp-ettoufee.md
- site/products/heat-and-eat/smotherd-cabbage-pan.md
- site/products/heat-and-eat/stuffed-potato.md
- site/products/heat-and-eat/vegetable-soup.md
- site/products/heat-and-eat/white-beans.md
- site/products/heat-and-eat/yam-pan.md
- site/products/sausage-and-smoked-meats/bacon-apple-maple.md
- site/products/sausage-and-smoked-meats/brown-sugar-syrup-smoked.md
- site/products/sausage-and-smoked-meats/caution-hot-smoked-sausage.md
- site/products/sausage-and-smoked-meats/deer-jalapeno-pepperjack-smoked.md
- site/products/sausage-and-smoked-meats/green-onion-and-garlic-smoked-sausage.md
- site/products/sausage-and-smoked-meats/green-onion-chicken.md
- site/products/sausage-and-smoked-meats/jalapeno-smoked-pork-sausage.md
- site/products/sausage-and-smoked-meats/mild-slim-sticks.md
- site/products/sausage-and-smoked-meats/pork-andouille.md
- site/products/sausage-and-smoked-meats/rabbit-pork-smoked.md
- site/products/sausage-and-smoked-meats/smoked-deer-and-pork-sausage.md
- site/products/sausage-and-smoked-meats/smoked-green-onion-sausage.md
- site/products/sausage-and-smoked-meats/smoked-greenonion-garlic-jalapeno.md
- site/products/sausage-and-smoked-meats/smoked-jalapeno-pepperjack-cheese.md
- site/products/sausage-and-smoked-meats/smoked-mixed-sausage.md
- site/products/seafood.md
- site/products/smoked meats/ham-hocks.md
- site/products/smoked meats/pork-ribs.md
- site/products/smoked meats/pork-tasso.md
- site/products/smoked meats/pork-wild-wings.md
- site/products/smoked meats/slab-bacon.md
- site/products/smoked meats/turkey-necks.md
- site/products/smoked meats/turkey-wings.md
